config/routes.rb
Rails.application.routes.draw do
  devise_for :users, sign_out_via: [:get, :post]

  namespace :api, defaults: { format: :json } do
    post 'auth/login', to: 'authentication#login'
    resources :users, only: %i[create update destroy] do
      resources :posts, only: [:index, :show] do
        resources :comments, only: [:index, :create]
    end
   end
  end
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :create, :new, :destroy] do
      resources :comments, only: [:create, :new, :destroy]
        resources :likes, only: [:create]
    end
  end
    root to: 'users#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :likes, foreign_key: :author_id, dependent: :destroy
  has_many :comments, foreign_key: :author_id, dependent: :destroy

  validates :name, presence: true, length: { minimum: 3, maximum: 20 }
  # validates :bio, presence: true, length: { minimum: 3, maximum: 150 }
  # validates :posts_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def check_last_three_posts
    posts.limit(3).order(created_at: :desc)
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  def index
    @users = User.all
    render json: @users, status: :ok
  end

  def show
    @user = User.find(params[:id])
    render json: @user, status: :ok
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  def index
    @users = User.all
    render json: @users, status: :ok
  end

  def show
    @user = User.find(params[:id])
    render json: @user, status: :ok
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = current_user
  end
end

app/views/users/index.html.erb
<section class='user-section'>
<h3>These are all the active users</h3>
  <ul class='user-container'>
<% @users.each do |user| %>
    <li class='user-index-card'>
      <img class='profile-index-photo' src='<%= user.photo %>' alt="<%= user.name %>'s profile picture" />
      <div class='user-index-container'>
        <h2><%= link_to user.name, user_path(user.id) %></h2>
        <p>Posts: <%= user.posts.count %></p>
      </div>
    </li>
<% end %>
  </ul>
</section>

app/views/users/show.html.erb
<section class='show-view'>
  

  <section class='user-header-section'>
    <img src='<%= @user.photo %>' alt="<%= @user.name %>'s profile picture"/>
    <div>
      <h2><%= @user.name %></h2>
      <p>
        <%= @user.posts.count %>
        <img class='post-icon' src="https://img.icons8.com/external-outline-juicy-fish/60/null/external-write-contact-us-outline-outline-juicy-fish.png"/>
      </p>
    </div>
  </section>

  <section class="configurations add-post-container">
    <h3><%= link_to 'User configurations', edit_user_registration_path %></h3>
  </section>

  <section class='bio-section'>
    <h3>Biography</h3>
    <p><%= @user.bio %></p>
  </section>
  
    <ul class='post-list-single-user'>
  <% @user.check_last_three_posts.each do |post| %>
      <li>
        <div class='post-info-data'>
          <h3><%= link_to post.title, user_post_path(@user, post) %></h3>
          <p><%= post.text %></p>
        </div>

        <div class='user-post-counters'>
          <div>
            <img class='post-counter-icon' src="https://img.icons8.com/ios/50/null/comments.png"/>
            <p class='post-counter'><%= post.comments.count %></p>
          </div>

          <div>
            <img class='post-counter-icon' src="https://img.icons8.com/sf-ultralight/50/null/good-quality.png"/>
            <p class='post-counter'><%= post.likes_counter %></p>
          </div>
        </div>
      </li>
  <% end %>
    </ul>

  <button class='see-posts'>
  <%= link_to 'See all posts', user_posts_path(@user) %>
  </button>

</section>