config/routes.rb
Rails.application.routes.draw do
  devise_for :users, sign_out_via: [:get, :post]

  namespace :api, defaults: { format: :json } do
    post 'auth/login', to: 'authentication#login'
    resources :users, only: %i[create update destroy] do
      resources :posts, only: [:index, :show] do
        resources :comments, only: [:index, :create]
    end
   end
  end
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :create, :new, :destroy] do
      resources :comments, only: [:create, :new, :destroy]
        resources :likes, only: [:create]
    end
  end
    root to: 'users#index'
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :likes, foreign_key: :post_id, dependent: :destroy
  has_many :comments, foreign_key: :post_id, dependent: :destroy
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  after_save :update_posts_counter

  # validates :title, presence: true, length: { minimum: 3, maximum: 250 }
  # validates :text, presence: true, length: { minimum: 3, maximum: 250 }

  def check_last_five_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_posts_counter
    author.update(posts_counter: author.posts.count)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  before_action :authorize_request

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.order(created_at: :desc).includes(:comments)

    json_response(@posts)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
  end

  def show
    @post = Post.includes(:comments, :likes).find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user

    @post.save
    redirect_to user_posts_path(current_user)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    @post.update(post_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:id]).destroy

    redirect_to root_path, status: :see_other
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/_form.html.erb
<%= form_with model: @post do |form| %>
<div class="edit-card card-post-container">
  <div class='locator-field'>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% post.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class='locator-field'>
    <%= form.label :Text %><br>
    <%= form.text_area :text %><br>
    <% post.errors.full_messages_for(:text).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class='custom-btn'>
    <%= form.submit "Submit Post" %>
  </div>
</div>
<% end %>

app/views/posts/edit.html.erb
<h1 class='edit'>Edit Post</h1>

<%= render "form", post: @post %>

app/views/posts/index.html.erb
<section class='show-view'>
    <section class='user-header-section'>
    <img src='<%= @user.photo %>' alt="<%= @user.name %>'s profile picture"/>
    <div>
      <h2><%= @user.name %></h2>
      <p>
        Posts:
        <%= @user.posts.length %>
      </p>
    </div>
    </section>
    <h3 class='add-post-container'>
    <%= link_to 'Add a new post...', new_post_path %>
    <img class='post-icon' src="https://img.icons8.com/external-outline-juicy-fish/60/null/external-write-contact-us-outline-outline-juicy-fish.png"/>
    </h3>
    <ul class='post-list-single-user'>
    <% @user.posts.each do |post| %>
        <li>
          <div class='post-info-data'>
            <h3><%= link_to post.title, user_post_path(post.author_id, post) %></h3>
            <p><%= post.text %></p>
          </div>

        <div class='user-post-counters'>
          <div>
            <img class='post-counter-icon' src="https://img.icons8.com/ios/50/null/comments.png"/>
            <p class='post-counter'>Comments:<%= post.comments.count || 0 %></p>
          </div>

          <div>
            <img class='post-counter-icon' src="https://img.icons8.com/sf-ultralight/50/null/good-quality.png"/>
            <p class='post-counter'>Likes:<%= post.likes_counter || 0 %></p>
          </div>
          <h5><%= render partial: 'likes/form', locals: {post: post} %></h5>
        </div>

        <div class='comments-section'>
          <%= render partial: 'comments/form', locals: {post: post} %>
        <% post.check_last_five_comments.each do |comment| %>
          <p><%= comment.author.name %>: <%= comment.text %></p>
        <% end %>
        </div>
    
        </li>
    <% end %>
    </ul>
</section>

app/views/posts/new.html.erb
<section class='post-section'>
<div class='card-post-container'>
<h2 class='create-post'>Share your thoughts by adding a <strong class='np'>new post</strong></h2>
<%= form_with model: @post do |form| %>
  <div class='post-field'>
    <%= form.text_field :title, placeholder: 'Title'  %>
  </div>

  <div class='post-field post-field-text'>
    <%= form.text_field :text, placeholder: 'Post content...' %>
  </div>

  <div class='post-field-submit'>
    <%= form.submit "Submit Post" %>
  </div>
<% end %>
</div>
</section>

app/views/posts/show.html.erb
<section class='single-post'>
  <section class='single-post_body'>
    <div>
        <div class='single-post-header'>
            <h2><%= @post.title %> by <%= @post.author.name %></h2>
            <div class='single-post-counters'> 
                <p>
                <img class='post-counter-icon' src="https://img.icons8.com/ios/50/null/comments.png"/>
                Comments:<%=@post.comments.count %>
                </p>

                <p>
                <img class='post-counter-icon' src="https://img.icons8.com/sf-ultralight/50/null/good-quality.png"/>
                Likes:<%=@post.likes_counter %>
                </p>
            </div>
        </div>
        <p class='single-text'><%= @post.text %></p>
    </div>

  <ul class='comments-section single-csection'>
    <h3>Comments</h3>
    <% @post.comments.each do |comment| %>
      <li class='single-li'>
        <h4><%= comment.author.name %>: <%= comment.text %></h4>
        <h5>Activity date:<%= comment.created_at %></h5>
        <% if can? :destroy, comment %>
            <%= link_to "delete", comment_path(comment), data: {
              turbo_method: :delete,
              turbo_confirm: "Do you want to delete de comment?"
            } %>
          <% end %>
      </li>
    <% end %>
  </ul>

  <ul class='customizable-post'>
      <li>
       <% if can? :update, @post %>
         <%= link_to "Edit post", edit_post_path(@post) %>
       <% end %>
     </li>
     <li>
       <% if can? :destroy, @post %>
         <%= link_to "Delete post", post_path(@post), data: {
                         turbo_method: :delete,
                         turbo_confirm: "Are you sure you want to delete this post?"
                      } %>
       <% end %>
     </li>
  </ul>
  </section>
</section>